@startuml Sequence

hide footbox

mainframe **Interaksi** Analisis Portofolio

actor Investor as I
boundary "Halaman Detail Portofolio" as PDP
boundary "Halaman Analisis Portofolio" as PAP
control "Portfolio Control" as PC
entity "Portfolio" as P
entity "PortfolioAnalysis" as PA

' User initiates analysis from detail page
I -> PDP : showPortfolioAnalysis(portfolioId)
activate PDP

PDP -> PAP : show(portfolioId)
activate PAP
deactivate PDP

' Control layer retrieves portfolio data
PAP -> PC : getPortfolioAnalysis(portfolioId)
activate PC

PC -> P ** : get(portfolioId)
activate P

alt portfolio found
  P -->> PC : Portfolio
else portfolio not found
  P -->> PC : error
  PC -->> PAP : error
end


' Retrieve analysis data if portfolio retrieval succeeded
PC -> P : getAnalysis(portfolioId)
activate P

P -> P : analyze
activate P
deactivate P

P -> PA  ** : getByPortfolioId(portfolioId)
activate PA

PA -->> P : PortfolioAnalysis[]
deactivate PA

P -->> PC : PortfolioAnalysis[]
deactivate P

PC -->> PAP : PortfolioAnalysis[]
deactivate PC

PAP -> PAP : showAnalysis()
activate PAP
deactivate PAP

@enduml
