@startuml Sequence

hide footbox
autoactivate on

mainframe **sd** Analisis Portofolio

actor Investor as I
boundary "Halaman Detail Portofolio" as HDP
boundary "Halaman Analisis Portofolio" as HAP
control "Portofolio Control" as PC
entity "Portofolio" as P

I -> HDP : showPortofolioAnalysis(portofolioId)

HDP -> HAP : show(portofolioId)

deactivate HDP

HAP -> PC : getByPortofolioId(portofolioId)

PC -> P : getByPortofolioId(portofolioId)

P -->> PC : portofolioAnalysis, error

PC -->> HAP : portofolioAnalysis, error

alt error != null
  HAP -> HAP : show Analysis
  deactivate HAP
else error = null
  HAP -> HAP : showError
  deactivate HAP
end

@enduml