@startuml Sequence

hide footbox
autoactivate on

mainframe **sd** Detail Portofolio

actor Investor as I
boundary "Halaman Dashboard" as HD
boundary "Tab Portofolio" as TP
boundary "Halaman Detail Portofolio" as HDP
control "Portofolio Control" as PC
entity "Portofolio" as P

I -> HD : showPortofolioTab

HD -> TP : show

deactivate HD

I -> TP : showPortofolioDetail(idPortofolio)
TP -> HDP : show(idPortofolio)

deactivate TP
deactivate TP

HDP -> PC : getPortofolio(idPortofolio) 

PC -> P : getPortofolio(idPortofolio)

P --> PC : Portofolio, error

PC --> HDP : Portofolio, error

alt error != null
  HDP -> HDP : updateUI
  deactivate HDP
else error = null
  HDP -> HDP : showError(error)
  deactivate HDP
end

@enduml