@startuml Sequence

hide footbox
autoactivate on

mainframe **sd** Detail Portofolio

actor Investor as I
boundary "Halaman Dashboard" as HD
boundary "Tab Portofolio" as TP
boundary "Halaman Detail Portofolio" as HDP
control "Portofolio Control" as PC
entity "Portofolio" as P

I -> HD : tampilkanTabPortofolio

HD -> TP : tampilkan

deactivate HD

I -> TP : tampilkanDetailPortofolio(idPortofolio)
TP -> HDP : tampilkan(idPortofolio)

deactivate TP
deactivate TP

HDP -> PC : getPortofolio(idPortofolio) 

PC -> P : getPortofolio(idPortofolio)

P --> PC : Portofolio, error

PC --> HDP : Portofolio, error

alt error != null
  HDP -> HDP : updateUI
  deactivate HDA
else error = null
  HDP -> HDP : tampilkanError(error)
  deactivate HDA
end

@enduml