@startuml Sequence

hide footbox

mainframe **Interaksi** Detail Portofolio

actor Investor as I
boundary "Tab Portofolio" as TP
boundary "Halaman Detail Portofolio" as HDP
control "Porotofolio Control" as PC
entity "Portofolio" as P

I -> TP : showPortofolioDetail(id)
activate TP

TP -> HDP : show(id)
activate HDP
deactivate TP

HDP -> PC : getPortofolio(id)
activate PC

PC -> P ** : get(id)
activate P

alt portofolio found
  P -->> PC : portofolio
  PC -->> HDP : portofolio
  HDP -> HDP : showPortofolio
else portofolio not found
  P -->> PC : error
  deactivate P

  PC -->> HDP : error
  deactivate PC

  HDP -> HDP : showError
end

@enduml