@startuml Sequence

hide footbox
autoactivate on

mainframe **sd** Detail Aset

actor Investor as I
boundary "Halaman Detail Portoflio" as HDP
boundary "Halaman Detail Aset" as HDA
control "Aset Control" as AC
entity "Aset" as A

I -> HDP : showAssetDetail(idAset)

HDP -> HDA : show(idAset)

deactivate HDP

HDA -> AC : getAsset(idAset)

AC -> A : getAsset(idAset)

A -->> AC : asset, error

AC -->> HDA : asset, error

alt error != null
  HDA -> HDA : updateUI
  deactivate HDA
else error = null
  HDA -> HDA : showError(error)
  deactivate HDA
end

@enduml