@startuml Sequence

hide footbox

mainframe **Interaksi** Detail Aset

actor Investor as I
boundary "Halaman Detail Portoflio" as HDP
boundary "Halaman Detail Aset" as HDA
control "Asset Control" as AC
entity "Asset" as A

I -> HDP : showAssetDetail(id)
activate HDP

HDP -> HDA : show(id)
activate HDA
deactivate HDP

HDA -> AC : getAsset(id)
activate AC

AC -> A ** : get(id)
activate A

alt asset found
  A -->> AC : asset
  AC -->> HDA : asset
  HDA -> HDA : showAsset
else asset not found
  A -->> AC : error
  deactivate A

  AC -->> HDA : error
  deactivate AC

  HDA -> HDA : showError
end

@enduml