@startuml Sequence

skinparam maxMessageSize 250

hide footbox
autoactivate on

mainframe **sd** Edit Kepemilikan Aset

actor Investor as I
boundary "Modal Edit Aset" as PEA
boundary "Halaman Detail Portofolio" as HDP
control "Portofolio Control" as PC
entity "Portofolio" as P

I -> HDP : editAsset(idAset)
HDP -> PEA : show(idAset, idPortofolio)

loop error != null
  I -> PEA : submit(jumlah)
  PEA -> HDP : editOwnAsset(idAset, idPortofolio, jumlah)
  HDP -> PC : editOwnAsset(idAset, idPortofolio, jumlah)
  PC -> P : editOwnAsset(idAset, idPortofolio, jumlah)
  P --> PC : ownAsset, error
  PC --> HDP : ownAsset, error

  opt error != null
    HDP -> PEA : showError(error)
    deactivate PEA
  end
end

HDP -> PEA : closeModal
deactivate PEA

@enduml