@startuml Sequence

skinparam maxMessageSize 250

hide footbox
autoactivate on

mainframe **sd** Edit Peringatan Harga

actor Investor as I
boundary "Modal Edit Peringatan Harga" as PEPH
boundary "Tab Peringatan Harga" as TPH
control "Peringatan Harga Control" as PHC
entity "Peringatan Harga" as PH

ref over I, PH : Lihat Daftar Peringatan Harga

I -> TPH : editPriceAlert(alertId)
TPH -> PEPH : tampilkan(alertId)

loop error != null
  I -> PEPH : submit(currency, priceTarget)
  PEPH -> TPH : editPriceAlert(alertId, currency, priceTarget)
  TPH -> PHC : editPriceAlert(alertId, currency, priceTarget)
  PHC -> PH : editPriceAlert(alertId, currency, priceTarget)
  PH --> PHC : priceAlert, error
  PHC --> TPH : priceAlert, error

  opt error != null
    TPH -> PEPH : showError
    deactivate PEPH
  end
end

TPH -> PEPH : closeModal
deactivate PEPH
@enduml