@startuml Sequence

skinparam maxMessageSize 250

hide footbox

mainframe **Interaction** Hapus Peringatan Harga

actor Investor as I
boundary "Tab Peringatan Harga" as TPH
boundary "Popup Hapus Peringatan Harga" as PHPH
control "Price Alert Control" as PAC
entity "PriceAlert" as PA

ref over I, PA : Lihat Daftar Peringatan Harga

I -> TPH : deletePriceAlert(id)
activate TPH

TPH -> PHPH : showPopup(id)
activate PHPH

I -> PHPH : confirm
activate PHPH

alt cancel
  PHPH -> PHPH : hidePopup
  activate PHPH
  deactivate PHPH
else confirm
  PHPH -> PAC : deletePriceAlert(id)
  activate PAC
end

  PAC -> PA ** : get(id)
  activate PA

  alt Price alert found
    PA -->> PAC : PriceAlert
  else Price alert not found
    PA -->> PAC : error
    deactivate PA
    PAC -->> PHPH : error
    PHPH -> PHPH : showError
    activate PHPH
    deactivate PHPH
  end

  PAC -> PA : delete
  activate PA

  PA -->> PAC : return
  deactivate PA

  PAC -->> PHPH : return

  PHPH -> TPH : updatePriceAlertList
  TPH -->> PHPH : return

PHPH -> PHPH : hidePopup
activate PHPH
deactivate PHPH
deactivate PHPH
deactivate PHPH



@enduml