@startuml Sequence

skinparam maxMessageSize 250

hide footbox

mainframe **Interaction** Hapus Kepemilikan Aset

actor Investor as I
boundary "Halaman Detail Portofolio" as HDP
boundary "Popup Hapus Aset" as PHA
control "Portofolio Control" as PC
entity "PortofolioAsset" as PA

ref over I, PA : Lihat Detail Portofolio

I -> HDP : deleteAsset(assetId)
activate HDP

HDP -> PHA : showPopup(assetId)
activate PHA

I -> PHA : confirm
activate PHA

alt cancel
  PHA -> PHA : hidePopup
  activate PHA
  deactivate PHA
else confirm
  PHA -> PC : deleteAsset(portofolioId, assetId)
  activate PC
end

  PC -> PA ** : get(portofolioId, assetId)
  activate PA

  alt Asset found
    PA -->> PC : PortofolioAsset
  else Asset not found
    PA -->> PC : error
    deactivate PA
    PC -->> PHA : error
    PHA -> PHA : showError
    activate PHA
    deactivate PHA
  end

  PC -> PA : delete
  activate PA

  PA -->> PC : return
  deactivate PA

  PC -->> PHA : return

  PHA -> HDP : updatePortofolioAssetList
  HDP -->> PHA : return

PHA -> PHA : hidePopup
activate PHA
deactivate PHA
deactivate PHA
deactivate PHA



@enduml