@startuml Sequence

skinparam maxMessageSize 250

hide footbox
autoactivate on

mainframe **sd** Hapus Portofolio

actor Investor as I
boundary "Popup Hapus Portofolio" as PHP
boundary "Tab Portofolio" as TP
control "Portofolio Control" as PC
entity "Portofolio" as P

I -> TP : deletePortofolio(portofolioId)
TP -> PHP : show

I -> PHP : comfirm/cancel

PHP -> PHP : close
deactivate PHP

opt konfirmasi
  PHP -> TP : deletePortofolio(portofolioId)
  TP -> PC : deletePortofolio(portofolioId)
  PC -> PH : deletePortofolio(portofolioId)
  PH --> PC : error
  PC --> TP : error

  alt error != null
    TP -> TP : showError(error)
    deactivate TP
  else error = null
    TP -> TP : updateUI
    deactivate TP
  end
end

deactivate PHP
deactivate PHP

@enduml