@startuml Sequence

skinparam maxMessageSize 250

hide footbox
autoactivate on

mainframe **sd** Hapus Kepemilikan Aset

actor Investor as I
boundary "Popup Hapus Aset" as PHA
boundary "Halaman Detail Portofolio" as HDP
control "Portofolio Control" as PC
entity "Portofolio" as P

I -> HDP : deleteAsset(assetId)
HDP -> PHA : show

I -> PHA : confirm/cancel

PHA -> PHA : close
deactivate PHA

opt konfirmasi
  PHA -> HDP : deleteOwnAsset(assetId, portofolioId)
  HDP -> PC : deleteOwnAsset(assetId, portofolioId)
  PC -> P : deleteOwnAsset(assetId, portofolioId)
  P --> PC : error
  PC --> HDP : error

  alt error != null
    HDP -> HDP : showError(error)
    deactivate HDP
  else error = null
    HDP -> HDP : updateUI
    deactivate HDP
  end
end

deactivate PHA
deactivate PHA

@enduml