@startuml Sequence

skinparam maxMessageSize 250

hide footbox
autoactivate on

mainframe **sd** Hapus Peringatan Harga

actor Investor as I
boundary "Popup Hapus Peringatan Harga" as PHPH
boundary "Tab Peringatan Harga" as TPH
control "Peringatan Harga Control" as PHC
entity "Peringatan Harga" as PH

I -> TPH : deleteAsset(alertId)
TPH -> PHPH : show

I -> PHPH : confirm/cancel

PHPH -> PHPH : close
deactivate PHPH

opt konfirmasi
  PHPH -> TPH : deletePriceAlert(alertId)
  TPH -> PHC : deletePriceAlert(alertId)
  PHC -> PH : deletePriceAlert(alertId)
  PH --> PHC : error
  PHC --> TPH : error

  alt error != null
    TPH -> TPH : showError(error)
    deactivate TPH
  else error = null
    TPH -> TPH : updateUI
    deactivate TPH
  end
end

deactivate PHPH
deactivate PHPH



@enduml