@startuml Sequence

hide footbox
autoactivate on

mainframe **Interaction** Lihat Daftar Peringatan Harga

actor Investor as I
boundary "Halaman Dashboard" as HD
boundary "Tab Peringatan Harga" as TPH
control "Peringatan Harga Control" as PHC
entity "Peringatan Harga" as PH

I -> HD : openPriceAlert
HD -> TPH : show
TPH -> PHC : getPriceAlertByUserId(userId)
PHC -> PH ** : getByUserId(userId)
PH -->> PHC : priceAlert[]
PHC -->> TPH : priceAlert[]

alt priceAlertList.length = 0
  TPH -> TPH : showPlaceholderText
  deactivate TPH
else priceAlertList.length > 0
  TPH -> TPH : showPriceAlertList
  deactivate TPH
end

@enduml