@startuml Sequence

hide footbox
autoactivate on

mainframe **sd** Lihat Daftar Peringatan Harga

actor Investor as I
boundary "Halaman Dashboard" as HD
boundary "Tab Peringatan Harga" as TPH
control "Peringatan Harga Control" as PHC
entity "Peringatan Harga" as PH

I -> HD : openPriceAlert
HD -> TPH : show
TPH -> PHC : getAllPriceAlert(userId)
PHC -> PH : getAll(userId)
PH --> PHC : priceAlertList
PHC --> TPH : priceAlertList

alt priceAlertList.length = 0
  TPH -> TPH : tampilkanPesan
  deactivate TPH
else priceAlertList.length > 0
  TPH -> TPH : tampilkanPeringatanHarga
  deactivate TPH
end

@enduml