@startuml Sequence

hide footbox
autoactivate on

mainframe *sd* Lihat Daftar Portofolio

actor Investor as I
boundary "Halaman Dashboard" as HD
boundary "Tab Portofolio" as TP
control "Portofolio Control" as PC
entity "Portofolio" as P

I -> HD : openPortofolio
HD -> TP : show
TP -> PC : getPortofolioByUserId(userId)
PC -> P ** : getByUserId(userId)
P -->> PC : Portofolio[]
PC -->> TP : Portofolio[]

alt portofolioList.length = 0
  TP -> TP : showPlaceholderText
  deactivate TP
else portofolioList.length > 0
  TP -> TP : showPortofolioList
  deactivate TP
end

@enduml