@startuml Sequence

hide footbox
autoactivate on

mainframe **sd** Lihat Daftar Portofolio

actor Investor as I
boundary "Halaman Dashboard" as HD
boundary "Tab Portofolio" as TP
control "Portofolio Control" as PC
entity "Portofolio" as P

I -> HD : openPortofolio
HD -> TPH : show
TPH -> PHC : getAllPortofolio(userId)
PHC -> PH : getAll(userId)
PH --> PHC : portofolioList
PHC --> TPH : portofolioList

alt portofolioList.length = 0
  TPH -> TPH : tampilkanPesan
  deactivate TPH
else portofolioList.length > 0
  TPH -> TPH : tampilkanPortofolio
  deactivate TPH
end

@enduml