@startuml Sequence

hide footbox
autoactivate on

mainframe *sd* Lihat Daftar Portofolio

actor Investor as I
boundary "Halaman Dashboard" as HD
boundary "Tab Portofolio" as TP
control "Portofolio Control" as PC
entity "Portofolio" as P

I -> HD : openPortofolio
HD -> TP : show
TP -> PC : getAllPortofolio(userId)
PC -> P : getAll(userId)
P -->> PC : portofolioList
PC -->> TP : portofolioList

alt portofolioList.length = 0
  TP -> TP : tampilkanPesan
  deactivate TP
else portofolioList.length > 0
  TP -> TP : tampilkanPortofolio
  deactivate TP
end

@enduml