@startuml Sequence

hide footbox
autoactivate on

actor "Investor"
boundary "Button Logout" as BL
boundary "Popup Konfirmasi Logout" as PKL
control "Auth Control" as AC
entity "Auth Service" as ASR
entity "" as user


@enduml