@startuml Sequence

hide footbox
autoactivate on

actor "Investor" as I
boundary "Tombol Logout" as TL
boundary "Popup Konfirmasi Logout" as PKL
boundary "Halaman Login" as HL

I -> TL : logout

TL -> PKL : showPopup
deactivate TL

PKL -> PKL : hidePopup
deactivate PKL

I -> PKL : confirm

opt confirm
  PKL -> HL : show
end

deactivate PKL
deactivate PKL


@enduml