@startuml Sequence

hide footbox
autoactivate on

mainframe **Interaksi** Logout

actor "Investor" as I
boundary "Tombol Logout" as TL
boundary "Popup Konfirmasi Logout" as PKL
boundary "Halaman Login" as HL

I -> TL : logout

TL -> PKL : showPopup
deactivate TL

I -> PKL : confirm

PKL -> PKL : hidePopup
deactivate PKL


opt confirm
  PKL -> HL : show
end

deactivate PKL
deactivate PKL


@enduml