@startuml Sequence

hide footbox

mainframe **Interaksi** Lupa Password

actor "Pengguna"
boundary "Form Login" as FL
boundary "Form Lupa Password" as FLP
boundary "Form Reset Password" as FRP
boundary "Halaman Login" as HL
control "Auth Control" as AC
entity "User" as User
entity "UserResetPasswordToken" as URPT
entity "UserResetPasswordToken" as URPT2
entity "User" as User2
entity "EmailSender" as ES

Pengguna -> FLP : submit(email)
activate FLP

FLP -> AC : forgotPassword(email)
activate AC

AC -> AC : validate
activate AC
deactivate AC

alt valid
  AC -> User ** : getByEmail(email)
  activate User
else invalid
  AC -->> FLP : error
  FLP -> FLP : showError
  activate FLP
  deactivate FLP
end

alt user found
  User -->> AC : User
else user not found
  User -->> AC : error
  deactivate User

  AC -->> FLP : error
  FLP -> FLP : showError
  activate FLP
  deactivate FLP
end

AC -> URPT ** : new UserResetPasswordToken(userId)
activate URPT
URPT -->> AC : UserResetPasswordToken (token)
deactivate URPT

AC -> URPT : save
activate URPT
URPT -->> AC : return
deactivate URPT


AC -> ES : send(email, token)
activate ES
ES -->> AC : return
deactivate ES

AC -->> FLP : return
deactivate AC
deactivate FLP

Pengguna -> FRP : submit(token, password)
activate FRP

FRP -> AC : resetPassword(token, password)
activate AC

AC -> AC : validate
activate AC
deactivate AC

alt valid
  AC -> URPT2 ** : getByToken(token)
  activate URPT2
  URPT2 -->> AC : UserResetPasswordToken (userId)
  deactivate URPT2
else invalid
  AC -->> FRP : error
  FRP -> FRP : showError
  activate FRP
  deactivate FRP
end

AC -> User2 ** : get(userId)
activate User2
User2 -->> AC : User
deactivate User2

AC -> User2 : resetPassword(token, password)
activate User2
User2 -->> AC : return
deactivate User2

AC -->> FRP : return
deactivate AC

FRP -> HL : show
deactivate FRP
activate HL

@enduml