@startuml

hide footbox
autoactivate on
mainframe **sd** Lupa Password
skinparam maxMessageSize 200

actor "Pengguna" as P
boundary "Halaman Login" as HL
boundary "Halaman Lupa Password" as HLP
boundary "Halaman Reset Password" as HRP
control "Auth Control" as AC
entity "User" as user

HL -> HLP : show
deactivate HL
loop error != null
    P -> HLP: submit(email)
    HLP -> AC: forgotPassword(email)
    AC -> user: forgotPassword(email)
    user -> user: sendOtp(email, otp)
    user -->> AC: error
    AC -->> HLP: error
    opt error != null
        HLP -> HLP: showError
        deactivate HLP 
    end
end

deactivate user
deactivate HLP
deactivate HLP
P -> HRP: show(otp) 
P -> HRP: submit(newPassword)
HRP -> AC: resetPassword(userId, newPassword, otp)
AC -> user: resetPassword(userId, newPassword, otp) 
user -->> AC: error
AC -->> HRP: 

HRP -> HL : show
deactivate HRP

@enduml