@startuml Sequence

skinparam maxMessageSize 250

hide footbox
autoactivate on

mainframe **sd** Tambah Kepemilikan Aset

actor Investor as I
boundary "Modal Tambah Kepemilikan Aset" as PTKA
boundary "Halaman Detail Portofolio" as TDP
control "Portofolio Control" as PC
entity "Portofolio" as P

ref over I, P : Lihat Detail Portofolio

I -> TDP : addOwnAsset
TDP -> PTKA : show

loop error != null
  I -> PTKA : submit(assetId, quantity)
  PTKA -> TDP : addOwnAsset(assetId, quantity, userId)
  TDP -> PC : addOwnAsset(assetId, quantity, userId)
  PC -> P : addOwnAsset(assetId, quantity, userId)
  P -->> PC : ownAsset, error
  PC -->> TDP : ownAsset, error

'Validation step
PC -> PC : validate
activate PC
deactivate PC

alt invalid input
  PC -->> MBP : error
  MBP -->> MBP : showError
else valid input
  'Create and save the Portofolio entity
  PC -> P ** : new PortofolioAsset(portofolioId, assetId, quantity)
  activate P
  P -->> PC : PortofolioAsset
  deactivate P
end

TDP -> PTKA : closeModal
deactivate PTKA
@enduml